<?xml version="1.0" encoding="utf-8"?><Database Name="hutstaff_9_8" Class="viewKhenthuongdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=QNV96-PC\SQL2008;Initial Catalog=hutstaff_9_8;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="hutstaff_9_8ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.View_Khenthuong" Member="View_Khenthuongs">
    <Type Name="View_Khenthuong">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="shcc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_htkt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nkt_qtkt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="kt" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="hodem" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ttd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ma_dvql" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="dv" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="dcb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Expr1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kcb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Expr2" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>