#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutStaff.Administrator.Pages.BaoCao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hutstaff_9_8")]
	public partial class BaoCaoktDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsoyeu(soyeu instance);
    partial void Updatesoyeu(soyeu instance);
    partial void Deletesoyeu(soyeu instance);
    partial void Insertqtkt_tbl(qtkt_tbl instance);
    partial void Updateqtkt_tbl(qtkt_tbl instance);
    partial void Deleteqtkt_tbl(qtkt_tbl instance);
    partial void Insertdm_dv(dm_dv instance);
    partial void Updatedm_dv(dm_dv instance);
    partial void Deletedm_dv(dm_dv instance);
    partial void Insertdm_kt(dm_kt instance);
    partial void Updatedm_kt(dm_kt instance);
    partial void Deletedm_kt(dm_kt instance);
    #endregion
		
		public BaoCaoktDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["hutstaff_9_8ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaoCaoktDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaoCaoktDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaoCaoktDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaoCaoktDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<soyeu> soyeus
		{
			get
			{
				return this.GetTable<soyeu>();
			}
		}
		
		public System.Data.Linq.Table<qtkt_tbl> qtkt_tbls
		{
			get
			{
				return this.GetTable<qtkt_tbl>();
			}
		}
		
		public System.Data.Linq.Table<dm_dv> dm_dvs
		{
			get
			{
				return this.GetTable<dm_dv>();
			}
		}
		
		public System.Data.Linq.Table<dm_kt> dm_kts
		{
			get
			{
				return this.GetTable<dm_kt>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_search_kt")]
		public ISingleResult<sp_search_ktResult> sp_search_kt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string ma_dv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> shcc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tunam, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dennam, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> diencb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> khoicanbo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageIndex", DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Int")] ref System.Nullable<int> total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma_dv, shcc, ten, tunam, dennam, diencb, khoicanbo, pageIndex, pageSize, total);
			total = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((ISingleResult<sp_search_ktResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.soyeu")]
	public partial class soyeu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _shcc;
		
		private string _ma_dvql;
		
		private string _user;
		
		private string _pass;
		
		private System.Nullable<System.DateTime> _nvcqhn;
		
		private string _scmnd;
		
		private System.Nullable<int> _nc;
		
		private System.Nullable<System.DateTime> _ngay_cap;
		
		private string _hodem;
		
		private string _ten;
		
		private System.Nullable<decimal> _gt;
		
		private string _ttd;
		
		private System.Nullable<System.DateTime> _ntns;
		
		private System.Nullable<int> _ma_ns;
		
		private System.Nullable<int> _ma_qq;
		
		private string _ctqq;
		
		private string _dctt;
		
		private System.Nullable<int> _ma_dt;
		
		private System.Nullable<int> _ma_tg;
		
		private System.Nullable<int> _ma_gdtdcs;
		
		private System.Nullable<int> _ma_tpxt;
		
		private System.Nullable<System.DateTime> _ntgcm;
		
		private string _vdpc;
		
		private System.Nullable<System.DateTime> _nvbc;
		
		private string _cvdn;
		
		private System.Nullable<System.DateTime> _nvd;
		
		private System.Nullable<System.DateTime> _nct;
		
		private System.Nullable<System.DateTime> _nnn;
		
		private System.Nullable<System.DateTime> _nxn;
		
		private string _qh;
		
		private System.Nullable<int> _ma_tb;
		
		private System.Nullable<int> _ma_tdhv;
		
		private System.Nullable<int> _ma_tdth;
		
		private string _kn_tht;
		
		private System.Nullable<int> _ma_tdllct;
		
		private System.Nullable<int> _ma_tdqlnn;
		
		private string _nlstnk;
		
		private string _ma_ttsk;
		
		private string _ma_nm;
		
		private string _ddlsbt;
		
		private string _ttk;
		
		private System.Nullable<int> _dcb;
		
		private string _sbh;
		
		private System.Nullable<System.DateTime> _ndbh;
		
		private System.Nullable<int> _tthn;
		
		private string _email;
		
		private string _tel;
		
		private string _cthktt;
		
		private System.Nullable<int> _kcb;
		
		private System.Nullable<int> _ma_hktt;
		
		private System.Nullable<System.DateTime> _ngay_kthd;
		
		private string _ld_kthd;
		
		private System.Nullable<System.DateTime> _ngaybh;
		
		private System.Nullable<int> _thanggd;
		
		private System.Nullable<System.DateTime> _ngaybhct;
		
		private System.Nullable<System.DateTime> _mochuongtn;
		
		private System.Nullable<bool> _xoahs;
		
		private EntitySet<qtkt_tbl> _qtkt_tbls;
		
		private EntityRef<dm_dv> _dm_dv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnshccChanging(int value);
    partial void OnshccChanged();
    partial void Onma_dvqlChanging(string value);
    partial void Onma_dvqlChanged();
    partial void OnuserChanging(string value);
    partial void OnuserChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnnvcqhnChanging(System.Nullable<System.DateTime> value);
    partial void OnnvcqhnChanged();
    partial void OnscmndChanging(string value);
    partial void OnscmndChanged();
    partial void OnncChanging(System.Nullable<int> value);
    partial void OnncChanged();
    partial void Onngay_capChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_capChanged();
    partial void OnhodemChanging(string value);
    partial void OnhodemChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngtChanging(System.Nullable<decimal> value);
    partial void OngtChanged();
    partial void OnttdChanging(string value);
    partial void OnttdChanged();
    partial void OnntnsChanging(System.Nullable<System.DateTime> value);
    partial void OnntnsChanged();
    partial void Onma_nsChanging(System.Nullable<int> value);
    partial void Onma_nsChanged();
    partial void Onma_qqChanging(System.Nullable<int> value);
    partial void Onma_qqChanged();
    partial void OnctqqChanging(string value);
    partial void OnctqqChanged();
    partial void OndcttChanging(string value);
    partial void OndcttChanged();
    partial void Onma_dtChanging(System.Nullable<int> value);
    partial void Onma_dtChanged();
    partial void Onma_tgChanging(System.Nullable<int> value);
    partial void Onma_tgChanged();
    partial void Onma_gdtdcsChanging(System.Nullable<int> value);
    partial void Onma_gdtdcsChanged();
    partial void Onma_tpxtChanging(System.Nullable<int> value);
    partial void Onma_tpxtChanged();
    partial void OnntgcmChanging(System.Nullable<System.DateTime> value);
    partial void OnntgcmChanged();
    partial void OnvdpcChanging(string value);
    partial void OnvdpcChanged();
    partial void OnnvbcChanging(System.Nullable<System.DateTime> value);
    partial void OnnvbcChanged();
    partial void OncvdnChanging(string value);
    partial void OncvdnChanged();
    partial void OnnvdChanging(System.Nullable<System.DateTime> value);
    partial void OnnvdChanged();
    partial void OnnctChanging(System.Nullable<System.DateTime> value);
    partial void OnnctChanged();
    partial void OnnnnChanging(System.Nullable<System.DateTime> value);
    partial void OnnnnChanged();
    partial void OnnxnChanging(System.Nullable<System.DateTime> value);
    partial void OnnxnChanged();
    partial void OnqhChanging(string value);
    partial void OnqhChanged();
    partial void Onma_tbChanging(System.Nullable<int> value);
    partial void Onma_tbChanged();
    partial void Onma_tdhvChanging(System.Nullable<int> value);
    partial void Onma_tdhvChanged();
    partial void Onma_tdthChanging(System.Nullable<int> value);
    partial void Onma_tdthChanged();
    partial void Onkn_thtChanging(string value);
    partial void Onkn_thtChanged();
    partial void Onma_tdllctChanging(System.Nullable<int> value);
    partial void Onma_tdllctChanged();
    partial void Onma_tdqlnnChanging(System.Nullable<int> value);
    partial void Onma_tdqlnnChanged();
    partial void OnnlstnkChanging(string value);
    partial void OnnlstnkChanged();
    partial void Onma_ttskChanging(string value);
    partial void Onma_ttskChanged();
    partial void Onma_nmChanging(string value);
    partial void Onma_nmChanged();
    partial void OnddlsbtChanging(string value);
    partial void OnddlsbtChanged();
    partial void OnttkChanging(string value);
    partial void OnttkChanged();
    partial void OndcbChanging(System.Nullable<int> value);
    partial void OndcbChanged();
    partial void OnsbhChanging(string value);
    partial void OnsbhChanged();
    partial void OnndbhChanging(System.Nullable<System.DateTime> value);
    partial void OnndbhChanged();
    partial void OntthnChanging(System.Nullable<int> value);
    partial void OntthnChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OncthkttChanging(string value);
    partial void OncthkttChanged();
    partial void OnkcbChanging(System.Nullable<int> value);
    partial void OnkcbChanged();
    partial void Onma_hkttChanging(System.Nullable<int> value);
    partial void Onma_hkttChanged();
    partial void Onngay_kthdChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_kthdChanged();
    partial void Onld_kthdChanging(string value);
    partial void Onld_kthdChanged();
    partial void OnngaybhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybhChanged();
    partial void OnthanggdChanging(System.Nullable<int> value);
    partial void OnthanggdChanged();
    partial void OnngaybhctChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybhctChanged();
    partial void OnmochuongtnChanging(System.Nullable<System.DateTime> value);
    partial void OnmochuongtnChanged();
    partial void OnxoahsChanging(System.Nullable<bool> value);
    partial void OnxoahsChanged();
    #endregion
		
		public soyeu()
		{
			this._qtkt_tbls = new EntitySet<qtkt_tbl>(new Action<qtkt_tbl>(this.attach_qtkt_tbls), new Action<qtkt_tbl>(this.detach_qtkt_tbls));
			this._dm_dv = default(EntityRef<dm_dv>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shcc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int shcc
		{
			get
			{
				return this._shcc;
			}
			set
			{
				if ((this._shcc != value))
				{
					this.OnshccChanging(value);
					this.SendPropertyChanging();
					this._shcc = value;
					this.SendPropertyChanged("shcc");
					this.OnshccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_dvql", DbType="VarChar(6)")]
		public string ma_dvql
		{
			get
			{
				return this._ma_dvql;
			}
			set
			{
				if ((this._ma_dvql != value))
				{
					if (this._dm_dv.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_dvqlChanging(value);
					this.SendPropertyChanging();
					this._ma_dvql = value;
					this.SendPropertyChanged("ma_dvql");
					this.Onma_dvqlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user]", Storage="_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this.OnuserChanging(value);
					this.SendPropertyChanging();
					this._user = value;
					this.SendPropertyChanged("user");
					this.OnuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvcqhn", DbType="DateTime")]
		public System.Nullable<System.DateTime> nvcqhn
		{
			get
			{
				return this._nvcqhn;
			}
			set
			{
				if ((this._nvcqhn != value))
				{
					this.OnnvcqhnChanging(value);
					this.SendPropertyChanging();
					this._nvcqhn = value;
					this.SendPropertyChanged("nvcqhn");
					this.OnnvcqhnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scmnd", DbType="VarChar(10)")]
		public string scmnd
		{
			get
			{
				return this._scmnd;
			}
			set
			{
				if ((this._scmnd != value))
				{
					this.OnscmndChanging(value);
					this.SendPropertyChanging();
					this._scmnd = value;
					this.SendPropertyChanged("scmnd");
					this.OnscmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nc", DbType="Int")]
		public System.Nullable<int> nc
		{
			get
			{
				return this._nc;
			}
			set
			{
				if ((this._nc != value))
				{
					this.OnncChanging(value);
					this.SendPropertyChanging();
					this._nc = value;
					this.SendPropertyChanged("nc");
					this.OnncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap
		{
			get
			{
				return this._ngay_cap;
			}
			set
			{
				if ((this._ngay_cap != value))
				{
					this.Onngay_capChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap = value;
					this.SendPropertyChanged("ngay_cap");
					this.Onngay_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hodem", DbType="NVarChar(30)")]
		public string hodem
		{
			get
			{
				return this._hodem;
			}
			set
			{
				if ((this._hodem != value))
				{
					this.OnhodemChanging(value);
					this.SendPropertyChanging();
					this._hodem = value;
					this.SendPropertyChanged("hodem");
					this.OnhodemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(20)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gt", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> gt
		{
			get
			{
				return this._gt;
			}
			set
			{
				if ((this._gt != value))
				{
					this.OngtChanging(value);
					this.SendPropertyChanging();
					this._gt = value;
					this.SendPropertyChanged("gt");
					this.OngtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttd", DbType="NVarChar(50)")]
		public string ttd
		{
			get
			{
				return this._ttd;
			}
			set
			{
				if ((this._ttd != value))
				{
					this.OnttdChanging(value);
					this.SendPropertyChanging();
					this._ttd = value;
					this.SendPropertyChanged("ttd");
					this.OnttdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ntns", DbType="DateTime")]
		public System.Nullable<System.DateTime> ntns
		{
			get
			{
				return this._ntns;
			}
			set
			{
				if ((this._ntns != value))
				{
					this.OnntnsChanging(value);
					this.SendPropertyChanging();
					this._ntns = value;
					this.SendPropertyChanged("ntns");
					this.OnntnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_ns", DbType="Int")]
		public System.Nullable<int> ma_ns
		{
			get
			{
				return this._ma_ns;
			}
			set
			{
				if ((this._ma_ns != value))
				{
					this.Onma_nsChanging(value);
					this.SendPropertyChanging();
					this._ma_ns = value;
					this.SendPropertyChanged("ma_ns");
					this.Onma_nsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_qq", DbType="Int")]
		public System.Nullable<int> ma_qq
		{
			get
			{
				return this._ma_qq;
			}
			set
			{
				if ((this._ma_qq != value))
				{
					this.Onma_qqChanging(value);
					this.SendPropertyChanging();
					this._ma_qq = value;
					this.SendPropertyChanged("ma_qq");
					this.Onma_qqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctqq", DbType="NVarChar(100)")]
		public string ctqq
		{
			get
			{
				return this._ctqq;
			}
			set
			{
				if ((this._ctqq != value))
				{
					this.OnctqqChanging(value);
					this.SendPropertyChanging();
					this._ctqq = value;
					this.SendPropertyChanged("ctqq");
					this.OnctqqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dctt", DbType="NVarChar(200)")]
		public string dctt
		{
			get
			{
				return this._dctt;
			}
			set
			{
				if ((this._dctt != value))
				{
					this.OndcttChanging(value);
					this.SendPropertyChanging();
					this._dctt = value;
					this.SendPropertyChanged("dctt");
					this.OndcttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_dt", DbType="Int")]
		public System.Nullable<int> ma_dt
		{
			get
			{
				return this._ma_dt;
			}
			set
			{
				if ((this._ma_dt != value))
				{
					this.Onma_dtChanging(value);
					this.SendPropertyChanging();
					this._ma_dt = value;
					this.SendPropertyChanged("ma_dt");
					this.Onma_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tg", DbType="Int")]
		public System.Nullable<int> ma_tg
		{
			get
			{
				return this._ma_tg;
			}
			set
			{
				if ((this._ma_tg != value))
				{
					this.Onma_tgChanging(value);
					this.SendPropertyChanging();
					this._ma_tg = value;
					this.SendPropertyChanged("ma_tg");
					this.Onma_tgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_gdtdcs", DbType="Int")]
		public System.Nullable<int> ma_gdtdcs
		{
			get
			{
				return this._ma_gdtdcs;
			}
			set
			{
				if ((this._ma_gdtdcs != value))
				{
					this.Onma_gdtdcsChanging(value);
					this.SendPropertyChanging();
					this._ma_gdtdcs = value;
					this.SendPropertyChanged("ma_gdtdcs");
					this.Onma_gdtdcsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tpxt", DbType="Int")]
		public System.Nullable<int> ma_tpxt
		{
			get
			{
				return this._ma_tpxt;
			}
			set
			{
				if ((this._ma_tpxt != value))
				{
					this.Onma_tpxtChanging(value);
					this.SendPropertyChanging();
					this._ma_tpxt = value;
					this.SendPropertyChanged("ma_tpxt");
					this.Onma_tpxtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ntgcm", DbType="DateTime")]
		public System.Nullable<System.DateTime> ntgcm
		{
			get
			{
				return this._ntgcm;
			}
			set
			{
				if ((this._ntgcm != value))
				{
					this.OnntgcmChanging(value);
					this.SendPropertyChanging();
					this._ntgcm = value;
					this.SendPropertyChanged("ntgcm");
					this.OnntgcmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vdpc", DbType="NVarChar(100)")]
		public string vdpc
		{
			get
			{
				return this._vdpc;
			}
			set
			{
				if ((this._vdpc != value))
				{
					this.OnvdpcChanging(value);
					this.SendPropertyChanging();
					this._vdpc = value;
					this.SendPropertyChanged("vdpc");
					this.OnvdpcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvbc", DbType="DateTime")]
		public System.Nullable<System.DateTime> nvbc
		{
			get
			{
				return this._nvbc;
			}
			set
			{
				if ((this._nvbc != value))
				{
					this.OnnvbcChanging(value);
					this.SendPropertyChanging();
					this._nvbc = value;
					this.SendPropertyChanged("nvbc");
					this.OnnvbcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvdn", DbType="NVarChar(100)")]
		public string cvdn
		{
			get
			{
				return this._cvdn;
			}
			set
			{
				if ((this._cvdn != value))
				{
					this.OncvdnChanging(value);
					this.SendPropertyChanging();
					this._cvdn = value;
					this.SendPropertyChanged("cvdn");
					this.OncvdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nvd", DbType="DateTime")]
		public System.Nullable<System.DateTime> nvd
		{
			get
			{
				return this._nvd;
			}
			set
			{
				if ((this._nvd != value))
				{
					this.OnnvdChanging(value);
					this.SendPropertyChanging();
					this._nvd = value;
					this.SendPropertyChanged("nvd");
					this.OnnvdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nct", DbType="DateTime")]
		public System.Nullable<System.DateTime> nct
		{
			get
			{
				return this._nct;
			}
			set
			{
				if ((this._nct != value))
				{
					this.OnnctChanging(value);
					this.SendPropertyChanging();
					this._nct = value;
					this.SendPropertyChanged("nct");
					this.OnnctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nnn", DbType="DateTime")]
		public System.Nullable<System.DateTime> nnn
		{
			get
			{
				return this._nnn;
			}
			set
			{
				if ((this._nnn != value))
				{
					this.OnnnnChanging(value);
					this.SendPropertyChanging();
					this._nnn = value;
					this.SendPropertyChanged("nnn");
					this.OnnnnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nxn", DbType="DateTime")]
		public System.Nullable<System.DateTime> nxn
		{
			get
			{
				return this._nxn;
			}
			set
			{
				if ((this._nxn != value))
				{
					this.OnnxnChanging(value);
					this.SendPropertyChanging();
					this._nxn = value;
					this.SendPropertyChanged("nxn");
					this.OnnxnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qh", DbType="NVarChar(20)")]
		public string qh
		{
			get
			{
				return this._qh;
			}
			set
			{
				if ((this._qh != value))
				{
					this.OnqhChanging(value);
					this.SendPropertyChanging();
					this._qh = value;
					this.SendPropertyChanged("qh");
					this.OnqhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tb", DbType="Int")]
		public System.Nullable<int> ma_tb
		{
			get
			{
				return this._ma_tb;
			}
			set
			{
				if ((this._ma_tb != value))
				{
					this.Onma_tbChanging(value);
					this.SendPropertyChanging();
					this._ma_tb = value;
					this.SendPropertyChanged("ma_tb");
					this.Onma_tbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tdhv", DbType="Int")]
		public System.Nullable<int> ma_tdhv
		{
			get
			{
				return this._ma_tdhv;
			}
			set
			{
				if ((this._ma_tdhv != value))
				{
					this.Onma_tdhvChanging(value);
					this.SendPropertyChanging();
					this._ma_tdhv = value;
					this.SendPropertyChanged("ma_tdhv");
					this.Onma_tdhvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tdth", DbType="Int")]
		public System.Nullable<int> ma_tdth
		{
			get
			{
				return this._ma_tdth;
			}
			set
			{
				if ((this._ma_tdth != value))
				{
					this.Onma_tdthChanging(value);
					this.SendPropertyChanging();
					this._ma_tdth = value;
					this.SendPropertyChanged("ma_tdth");
					this.Onma_tdthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kn_tht", DbType="NVarChar(100)")]
		public string kn_tht
		{
			get
			{
				return this._kn_tht;
			}
			set
			{
				if ((this._kn_tht != value))
				{
					this.Onkn_thtChanging(value);
					this.SendPropertyChanging();
					this._kn_tht = value;
					this.SendPropertyChanged("kn_tht");
					this.Onkn_thtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tdllct", DbType="Int")]
		public System.Nullable<int> ma_tdllct
		{
			get
			{
				return this._ma_tdllct;
			}
			set
			{
				if ((this._ma_tdllct != value))
				{
					this.Onma_tdllctChanging(value);
					this.SendPropertyChanging();
					this._ma_tdllct = value;
					this.SendPropertyChanged("ma_tdllct");
					this.Onma_tdllctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tdqlnn", DbType="Int")]
		public System.Nullable<int> ma_tdqlnn
		{
			get
			{
				return this._ma_tdqlnn;
			}
			set
			{
				if ((this._ma_tdqlnn != value))
				{
					this.Onma_tdqlnnChanging(value);
					this.SendPropertyChanging();
					this._ma_tdqlnn = value;
					this.SendPropertyChanged("ma_tdqlnn");
					this.Onma_tdqlnnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nlstnk", DbType="NVarChar(255)")]
		public string nlstnk
		{
			get
			{
				return this._nlstnk;
			}
			set
			{
				if ((this._nlstnk != value))
				{
					this.OnnlstnkChanging(value);
					this.SendPropertyChanging();
					this._nlstnk = value;
					this.SendPropertyChanged("nlstnk");
					this.OnnlstnkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_ttsk", DbType="NVarChar(30)")]
		public string ma_ttsk
		{
			get
			{
				return this._ma_ttsk;
			}
			set
			{
				if ((this._ma_ttsk != value))
				{
					this.Onma_ttskChanging(value);
					this.SendPropertyChanging();
					this._ma_ttsk = value;
					this.SendPropertyChanged("ma_ttsk");
					this.Onma_ttskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nm", DbType="NVarChar(10)")]
		public string ma_nm
		{
			get
			{
				return this._ma_nm;
			}
			set
			{
				if ((this._ma_nm != value))
				{
					this.Onma_nmChanging(value);
					this.SendPropertyChanging();
					this._ma_nm = value;
					this.SendPropertyChanged("ma_nm");
					this.Onma_nmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ddlsbt", DbType="NVarChar(255)")]
		public string ddlsbt
		{
			get
			{
				return this._ddlsbt;
			}
			set
			{
				if ((this._ddlsbt != value))
				{
					this.OnddlsbtChanging(value);
					this.SendPropertyChanging();
					this._ddlsbt = value;
					this.SendPropertyChanged("ddlsbt");
					this.OnddlsbtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttk", DbType="NVarChar(255)")]
		public string ttk
		{
			get
			{
				return this._ttk;
			}
			set
			{
				if ((this._ttk != value))
				{
					this.OnttkChanging(value);
					this.SendPropertyChanging();
					this._ttk = value;
					this.SendPropertyChanged("ttk");
					this.OnttkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dcb", DbType="Int")]
		public System.Nullable<int> dcb
		{
			get
			{
				return this._dcb;
			}
			set
			{
				if ((this._dcb != value))
				{
					this.OndcbChanging(value);
					this.SendPropertyChanging();
					this._dcb = value;
					this.SendPropertyChanged("dcb");
					this.OndcbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbh", DbType="VarChar(20)")]
		public string sbh
		{
			get
			{
				return this._sbh;
			}
			set
			{
				if ((this._sbh != value))
				{
					this.OnsbhChanging(value);
					this.SendPropertyChanging();
					this._sbh = value;
					this.SendPropertyChanged("sbh");
					this.OnsbhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ndbh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ndbh
		{
			get
			{
				return this._ndbh;
			}
			set
			{
				if ((this._ndbh != value))
				{
					this.OnndbhChanging(value);
					this.SendPropertyChanging();
					this._ndbh = value;
					this.SendPropertyChanged("ndbh");
					this.OnndbhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tthn", DbType="Int")]
		public System.Nullable<int> tthn
		{
			get
			{
				return this._tthn;
			}
			set
			{
				if ((this._tthn != value))
				{
					this.OntthnChanging(value);
					this.SendPropertyChanging();
					this._tthn = value;
					this.SendPropertyChanged("tthn");
					this.OntthnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(100)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cthktt", DbType="NVarChar(255)")]
		public string cthktt
		{
			get
			{
				return this._cthktt;
			}
			set
			{
				if ((this._cthktt != value))
				{
					this.OncthkttChanging(value);
					this.SendPropertyChanging();
					this._cthktt = value;
					this.SendPropertyChanged("cthktt");
					this.OncthkttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kcb", DbType="Int")]
		public System.Nullable<int> kcb
		{
			get
			{
				return this._kcb;
			}
			set
			{
				if ((this._kcb != value))
				{
					this.OnkcbChanging(value);
					this.SendPropertyChanging();
					this._kcb = value;
					this.SendPropertyChanged("kcb");
					this.OnkcbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_hktt", DbType="Int")]
		public System.Nullable<int> ma_hktt
		{
			get
			{
				return this._ma_hktt;
			}
			set
			{
				if ((this._ma_hktt != value))
				{
					this.Onma_hkttChanging(value);
					this.SendPropertyChanging();
					this._ma_hktt = value;
					this.SendPropertyChanged("ma_hktt");
					this.Onma_hkttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_kthd", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_kthd
		{
			get
			{
				return this._ngay_kthd;
			}
			set
			{
				if ((this._ngay_kthd != value))
				{
					this.Onngay_kthdChanging(value);
					this.SendPropertyChanging();
					this._ngay_kthd = value;
					this.SendPropertyChanged("ngay_kthd");
					this.Onngay_kthdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ld_kthd", DbType="NVarChar(255)")]
		public string ld_kthd
		{
			get
			{
				return this._ld_kthd;
			}
			set
			{
				if ((this._ld_kthd != value))
				{
					this.Onld_kthdChanging(value);
					this.SendPropertyChanging();
					this._ld_kthd = value;
					this.SendPropertyChanged("ld_kthd");
					this.Onld_kthdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybh
		{
			get
			{
				return this._ngaybh;
			}
			set
			{
				if ((this._ngaybh != value))
				{
					this.OnngaybhChanging(value);
					this.SendPropertyChanging();
					this._ngaybh = value;
					this.SendPropertyChanged("ngaybh");
					this.OnngaybhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanggd", DbType="Int")]
		public System.Nullable<int> thanggd
		{
			get
			{
				return this._thanggd;
			}
			set
			{
				if ((this._thanggd != value))
				{
					this.OnthanggdChanging(value);
					this.SendPropertyChanging();
					this._thanggd = value;
					this.SendPropertyChanged("thanggd");
					this.OnthanggdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybhct", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaybhct
		{
			get
			{
				return this._ngaybhct;
			}
			set
			{
				if ((this._ngaybhct != value))
				{
					this.OnngaybhctChanging(value);
					this.SendPropertyChanging();
					this._ngaybhct = value;
					this.SendPropertyChanged("ngaybhct");
					this.OnngaybhctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mochuongtn", DbType="DateTime")]
		public System.Nullable<System.DateTime> mochuongtn
		{
			get
			{
				return this._mochuongtn;
			}
			set
			{
				if ((this._mochuongtn != value))
				{
					this.OnmochuongtnChanging(value);
					this.SendPropertyChanging();
					this._mochuongtn = value;
					this.SendPropertyChanged("mochuongtn");
					this.OnmochuongtnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xoahs", DbType="Bit")]
		public System.Nullable<bool> xoahs
		{
			get
			{
				return this._xoahs;
			}
			set
			{
				if ((this._xoahs != value))
				{
					this.OnxoahsChanging(value);
					this.SendPropertyChanging();
					this._xoahs = value;
					this.SendPropertyChanged("xoahs");
					this.OnxoahsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="soyeu_qtkt_tbl", Storage="_qtkt_tbls", ThisKey="shcc", OtherKey="shcc")]
		public EntitySet<qtkt_tbl> qtkt_tbls
		{
			get
			{
				return this._qtkt_tbls;
			}
			set
			{
				this._qtkt_tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dm_dv_soyeu", Storage="_dm_dv", ThisKey="ma_dvql", OtherKey="ma_dv", IsForeignKey=true)]
		public dm_dv dm_dv
		{
			get
			{
				return this._dm_dv.Entity;
			}
			set
			{
				dm_dv previousValue = this._dm_dv.Entity;
				if (((previousValue != value) 
							|| (this._dm_dv.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dm_dv.Entity = null;
						previousValue.soyeus.Remove(this);
					}
					this._dm_dv.Entity = value;
					if ((value != null))
					{
						value.soyeus.Add(this);
						this._ma_dvql = value.ma_dv;
					}
					else
					{
						this._ma_dvql = default(string);
					}
					this.SendPropertyChanged("dm_dv");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_qtkt_tbls(qtkt_tbl entity)
		{
			this.SendPropertyChanging();
			entity.soyeu = this;
		}
		
		private void detach_qtkt_tbls(qtkt_tbl entity)
		{
			this.SendPropertyChanging();
			entity.soyeu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.qtkt_tbl")]
	public partial class qtkt_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _shcc;
		
		private System.Nullable<int> _ma_htkt;
		
		private System.Nullable<System.DateTime> _nkt_qtkt;
		
		private string _soqd_qtkt;
		
		private string _ttk_qtkt;
		
		private EntityRef<soyeu> _soyeu;
		
		private EntityRef<dm_kt> _dm_kt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnshccChanging(System.Nullable<int> value);
    partial void OnshccChanged();
    partial void Onma_htktChanging(System.Nullable<int> value);
    partial void Onma_htktChanged();
    partial void Onnkt_qtktChanging(System.Nullable<System.DateTime> value);
    partial void Onnkt_qtktChanged();
    partial void Onsoqd_qtktChanging(string value);
    partial void Onsoqd_qtktChanged();
    partial void Onttk_qtktChanging(string value);
    partial void Onttk_qtktChanged();
    #endregion
		
		public qtkt_tbl()
		{
			this._soyeu = default(EntityRef<soyeu>);
			this._dm_kt = default(EntityRef<dm_kt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shcc", DbType="Int")]
		public System.Nullable<int> shcc
		{
			get
			{
				return this._shcc;
			}
			set
			{
				if ((this._shcc != value))
				{
					if (this._soyeu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnshccChanging(value);
					this.SendPropertyChanging();
					this._shcc = value;
					this.SendPropertyChanged("shcc");
					this.OnshccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_htkt", DbType="Int")]
		public System.Nullable<int> ma_htkt
		{
			get
			{
				return this._ma_htkt;
			}
			set
			{
				if ((this._ma_htkt != value))
				{
					if (this._dm_kt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_htktChanging(value);
					this.SendPropertyChanging();
					this._ma_htkt = value;
					this.SendPropertyChanged("ma_htkt");
					this.Onma_htktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nkt_qtkt", DbType="DateTime")]
		public System.Nullable<System.DateTime> nkt_qtkt
		{
			get
			{
				return this._nkt_qtkt;
			}
			set
			{
				if ((this._nkt_qtkt != value))
				{
					this.Onnkt_qtktChanging(value);
					this.SendPropertyChanging();
					this._nkt_qtkt = value;
					this.SendPropertyChanged("nkt_qtkt");
					this.Onnkt_qtktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soqd_qtkt", DbType="NVarChar(255)")]
		public string soqd_qtkt
		{
			get
			{
				return this._soqd_qtkt;
			}
			set
			{
				if ((this._soqd_qtkt != value))
				{
					this.Onsoqd_qtktChanging(value);
					this.SendPropertyChanging();
					this._soqd_qtkt = value;
					this.SendPropertyChanged("soqd_qtkt");
					this.Onsoqd_qtktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttk_qtkt", DbType="NVarChar(255)")]
		public string ttk_qtkt
		{
			get
			{
				return this._ttk_qtkt;
			}
			set
			{
				if ((this._ttk_qtkt != value))
				{
					this.Onttk_qtktChanging(value);
					this.SendPropertyChanging();
					this._ttk_qtkt = value;
					this.SendPropertyChanged("ttk_qtkt");
					this.Onttk_qtktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="soyeu_qtkt_tbl", Storage="_soyeu", ThisKey="shcc", OtherKey="shcc", IsForeignKey=true)]
		public soyeu soyeu
		{
			get
			{
				return this._soyeu.Entity;
			}
			set
			{
				soyeu previousValue = this._soyeu.Entity;
				if (((previousValue != value) 
							|| (this._soyeu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._soyeu.Entity = null;
						previousValue.qtkt_tbls.Remove(this);
					}
					this._soyeu.Entity = value;
					if ((value != null))
					{
						value.qtkt_tbls.Add(this);
						this._shcc = value.shcc;
					}
					else
					{
						this._shcc = default(Nullable<int>);
					}
					this.SendPropertyChanged("soyeu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dm_kt_qtkt_tbl", Storage="_dm_kt", ThisKey="ma_htkt", OtherKey="ma_kt", IsForeignKey=true)]
		public dm_kt dm_kt
		{
			get
			{
				return this._dm_kt.Entity;
			}
			set
			{
				dm_kt previousValue = this._dm_kt.Entity;
				if (((previousValue != value) 
							|| (this._dm_kt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dm_kt.Entity = null;
						previousValue.qtkt_tbls.Remove(this);
					}
					this._dm_kt.Entity = value;
					if ((value != null))
					{
						value.qtkt_tbls.Add(this);
						this._ma_htkt = value.ma_kt;
					}
					else
					{
						this._ma_htkt = default(Nullable<int>);
					}
					this.SendPropertyChanged("dm_kt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dm_dv")]
	public partial class dm_dv : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma_dv;
		
		private string _dv;
		
		private EntitySet<soyeu> _soyeus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_dvChanging(string value);
    partial void Onma_dvChanged();
    partial void OndvChanging(string value);
    partial void OndvChanged();
    #endregion
		
		public dm_dv()
		{
			this._soyeus = new EntitySet<soyeu>(new Action<soyeu>(this.attach_soyeus), new Action<soyeu>(this.detach_soyeus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_dv", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_dv
		{
			get
			{
				return this._ma_dv;
			}
			set
			{
				if ((this._ma_dv != value))
				{
					this.Onma_dvChanging(value);
					this.SendPropertyChanging();
					this._ma_dv = value;
					this.SendPropertyChanged("ma_dv");
					this.Onma_dvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dv", DbType="NVarChar(200)")]
		public string dv
		{
			get
			{
				return this._dv;
			}
			set
			{
				if ((this._dv != value))
				{
					this.OndvChanging(value);
					this.SendPropertyChanging();
					this._dv = value;
					this.SendPropertyChanged("dv");
					this.OndvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dm_dv_soyeu", Storage="_soyeus", ThisKey="ma_dv", OtherKey="ma_dvql")]
		public EntitySet<soyeu> soyeus
		{
			get
			{
				return this._soyeus;
			}
			set
			{
				this._soyeus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_soyeus(soyeu entity)
		{
			this.SendPropertyChanging();
			entity.dm_dv = this;
		}
		
		private void detach_soyeus(soyeu entity)
		{
			this.SendPropertyChanging();
			entity.dm_dv = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dm_kt")]
	public partial class dm_kt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_kt;
		
		private string _kt;
		
		private EntitySet<qtkt_tbl> _qtkt_tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_ktChanging(int value);
    partial void Onma_ktChanged();
    partial void OnktChanging(string value);
    partial void OnktChanged();
    #endregion
		
		public dm_kt()
		{
			this._qtkt_tbls = new EntitySet<qtkt_tbl>(new Action<qtkt_tbl>(this.attach_qtkt_tbls), new Action<qtkt_tbl>(this.detach_qtkt_tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_kt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_kt
		{
			get
			{
				return this._ma_kt;
			}
			set
			{
				if ((this._ma_kt != value))
				{
					this.Onma_ktChanging(value);
					this.SendPropertyChanging();
					this._ma_kt = value;
					this.SendPropertyChanged("ma_kt");
					this.Onma_ktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kt", DbType="NVarChar(100)")]
		public string kt
		{
			get
			{
				return this._kt;
			}
			set
			{
				if ((this._kt != value))
				{
					this.OnktChanging(value);
					this.SendPropertyChanging();
					this._kt = value;
					this.SendPropertyChanged("kt");
					this.OnktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dm_kt_qtkt_tbl", Storage="_qtkt_tbls", ThisKey="ma_kt", OtherKey="ma_htkt")]
		public EntitySet<qtkt_tbl> qtkt_tbls
		{
			get
			{
				return this._qtkt_tbls;
			}
			set
			{
				this._qtkt_tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_qtkt_tbls(qtkt_tbl entity)
		{
			this.SendPropertyChanging();
			entity.dm_kt = this;
		}
		
		private void detach_qtkt_tbls(qtkt_tbl entity)
		{
			this.SendPropertyChanging();
			entity.dm_kt = null;
		}
	}
	
	public partial class sp_search_ktResult
	{
		
		private int _shcc;
		
		private string _hoten;
		
		private string _dv;
		
		private string _tel;
		
		private string _email;
		
		public sp_search_ktResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shcc", DbType="Int NOT NULL")]
		public int shcc
		{
			get
			{
				return this._shcc;
			}
			set
			{
				if ((this._shcc != value))
				{
					this._shcc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(51)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this._hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dv", DbType="NVarChar(200)")]
		public string dv
		{
			get
			{
				return this._dv;
			}
			set
			{
				if ((this._dv != value))
				{
					this._dv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(100)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this._tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
