#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutStaff.Administrator.Pages.BaoCao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hutstaff_9_8")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["hutstaff_9_8ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<View_khenthuong> View_khenthuongs
		{
			get
			{
				return this.GetTable<View_khenthuong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_khenthuong")]
	public partial class View_khenthuong
	{
		
		private int _ma_kt;
		
		private string _kt;
		
		private int _Expr1;
		
		private System.Nullable<System.DateTime> _nkt_qtkt;
		
		private string _soqd_qtkt;
		
		private string _ttk_qtkt;
		
		private string _ma_dv;
		
		private string _dv;
		
		private int _shcc;
		
		private string _ten;
		
		private string _hodem;
		
		public View_khenthuong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_kt", DbType="Int NOT NULL")]
		public int ma_kt
		{
			get
			{
				return this._ma_kt;
			}
			set
			{
				if ((this._ma_kt != value))
				{
					this._ma_kt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kt", DbType="NVarChar(100)")]
		public string kt
		{
			get
			{
				return this._kt;
			}
			set
			{
				if ((this._kt != value))
				{
					this._kt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="Int NOT NULL")]
		public int Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nkt_qtkt", DbType="DateTime")]
		public System.Nullable<System.DateTime> nkt_qtkt
		{
			get
			{
				return this._nkt_qtkt;
			}
			set
			{
				if ((this._nkt_qtkt != value))
				{
					this._nkt_qtkt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soqd_qtkt", DbType="NVarChar(255)")]
		public string soqd_qtkt
		{
			get
			{
				return this._soqd_qtkt;
			}
			set
			{
				if ((this._soqd_qtkt != value))
				{
					this._soqd_qtkt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttk_qtkt", DbType="NVarChar(255)")]
		public string ttk_qtkt
		{
			get
			{
				return this._ttk_qtkt;
			}
			set
			{
				if ((this._ttk_qtkt != value))
				{
					this._ttk_qtkt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_dv", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string ma_dv
		{
			get
			{
				return this._ma_dv;
			}
			set
			{
				if ((this._ma_dv != value))
				{
					this._ma_dv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dv", DbType="NVarChar(200)")]
		public string dv
		{
			get
			{
				return this._dv;
			}
			set
			{
				if ((this._dv != value))
				{
					this._dv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shcc", DbType="Int NOT NULL")]
		public int shcc
		{
			get
			{
				return this._shcc;
			}
			set
			{
				if ((this._shcc != value))
				{
					this._shcc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(20)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hodem", DbType="NVarChar(30)")]
		public string hodem
		{
			get
			{
				return this._hodem;
			}
			set
			{
				if ((this._hodem != value))
				{
					this._hodem = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
