//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB_BK.Pages.TimKiem {
    
    
    public partial class Search {
        
        /// <summary>
        /// SearchForm1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QLCB_BK.Controls.TimKiem.SearchForm SearchForm1;
        
        /// <summary>
        /// SearchResult1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QLCB_BK.Controls.TimKiem.SearchResult SearchResult1;
    }
}
