#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutStaff.Administrator.Pages.BaoCao.dataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hutstaff_9_8")]
	public partial class viewKhenthuongdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public viewKhenthuongdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["hutstaff_9_8ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public viewKhenthuongdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public viewKhenthuongdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public viewKhenthuongdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public viewKhenthuongdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<View_Khenthuong> View_Khenthuongs
		{
			get
			{
				return this.GetTable<View_Khenthuong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Khenthuong")]
	public partial class View_Khenthuong
	{
		
		private int _id;
		
		private System.Nullable<int> _shcc;
		
		private System.Nullable<int> _ma_htkt;
		
		private System.Nullable<System.DateTime> _nkt_qtkt;
		
		private string _kt;
		
		private string _hodem;
		
		private string _ten;
		
		private string _ttd;
		
		private string _ma_dvql;
		
		private string _dv;
		
		private string _dcb;
		
		private System.Nullable<int> _Expr1;
		
		private string _kcb;
		
		private System.Nullable<int> _Expr2;
		
		public View_Khenthuong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shcc", DbType="Int")]
		public System.Nullable<int> shcc
		{
			get
			{
				return this._shcc;
			}
			set
			{
				if ((this._shcc != value))
				{
					this._shcc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_htkt", DbType="Int")]
		public System.Nullable<int> ma_htkt
		{
			get
			{
				return this._ma_htkt;
			}
			set
			{
				if ((this._ma_htkt != value))
				{
					this._ma_htkt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nkt_qtkt", DbType="DateTime")]
		public System.Nullable<System.DateTime> nkt_qtkt
		{
			get
			{
				return this._nkt_qtkt;
			}
			set
			{
				if ((this._nkt_qtkt != value))
				{
					this._nkt_qtkt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kt", DbType="NVarChar(100)")]
		public string kt
		{
			get
			{
				return this._kt;
			}
			set
			{
				if ((this._kt != value))
				{
					this._kt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hodem", DbType="NVarChar(30)")]
		public string hodem
		{
			get
			{
				return this._hodem;
			}
			set
			{
				if ((this._hodem != value))
				{
					this._hodem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(20)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttd", DbType="NVarChar(50)")]
		public string ttd
		{
			get
			{
				return this._ttd;
			}
			set
			{
				if ((this._ttd != value))
				{
					this._ttd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_dvql", DbType="VarChar(6)")]
		public string ma_dvql
		{
			get
			{
				return this._ma_dvql;
			}
			set
			{
				if ((this._ma_dvql != value))
				{
					this._ma_dvql = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dv", DbType="NVarChar(200)")]
		public string dv
		{
			get
			{
				return this._dv;
			}
			set
			{
				if ((this._dv != value))
				{
					this._dv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dcb", DbType="NVarChar(50)")]
		public string dcb
		{
			get
			{
				return this._dcb;
			}
			set
			{
				if ((this._dcb != value))
				{
					this._dcb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="Int")]
		public System.Nullable<int> Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kcb", DbType="NVarChar(50)")]
		public string kcb
		{
			get
			{
				return this._kcb;
			}
			set
			{
				if ((this._kcb != value))
				{
					this._kcb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr2", DbType="Int")]
		public System.Nullable<int> Expr2
		{
			get
			{
				return this._Expr2;
			}
			set
			{
				if ((this._Expr2 != value))
				{
					this._Expr2 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
